name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11' # الحفاظ على توافقية إصدار الجافا المستقر

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Clean Project
        run: flutter clean # استخدام فلوتر مباشرة للتنظيف لتجنب نقص ملفات جرادل

      - name: Build APK
        run: flutter build apk --release
